/* Optional replacement files: assets/sounds/<name>.wav, assets/bgm/stage.wav.
   Synthesized effects remain available when an optional file is missing. */
window.NekoAudio = class {
 constructor(settings){this.settings=settings;this.files=new Map();this.ctx=null;for(const name of ['pin','water','fire','extinguish','rope','impact','meow','enemy','fail','clear','button']){const sound=new Audio('assets/sounds/'+name+'.wav');sound.preload='auto';sound.failed=false;sound.addEventListener('error',()=>sound.failed=true);this.files.set(name,sound);}this.bgm=new Audio('assets/bgm/stage.wav');this.bgm.loop=true;this.bgm.preload='none';this.bgmFailed=false;this.bgm.addEventListener('error',()=>{this.bgmFailed=true;});}
 unlock(){try{this.ctx ||= new (window.AudioContext||window.webkitAudioContext)();this.ctx.resume();this.sync();}catch(e){}}
 sync(){this.bgm.volume=this.settings.volume*.45;if(this.settings.bgm&&!document.hidden&&this.ctx){this.bgm.play().catch(()=>{});}else this.bgm.pause();}
 tone(freq,duration=.15,type='sine',delay=0,volume=.12,end){if(!this.ctx)return;const t=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(end)o.frequency.exponentialRampToValueAtTime(end,t+duration);g.gain.setValueAtTime(.001,t);g.gain.linearRampToValueAtTime(volume*this.settings.volume,t+.012);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(this.ctx.destination);o.start(t);o.stop(t+duration);}
 play(name){if(!this.settings.se)return;let file=this.files.get(name);if(!file){file=new Audio('assets/sounds/'+name+'.wav');file.failed=false;file.addEventListener('error',()=>file.failed=true);this.files.set(name,file);}if(!file.failed&&file.readyState>=2){file.volume=this.settings.volume;file.currentTime=0;file.play().catch(()=>{});return;}const t=(...a)=>this.tone(...a);switch(name){case'clear':[523,659,784,1046].forEach((f,i)=>t(f,.24,'sine',i*.12));break;case'fail':t(330,.35,'triangle',0,.15,100);break;case'water':case'extinguish':for(let i=0;i<8;i++)t(500+Math.random()*700,.15,'sine',i*.07,.06,180);break;case'meow':t(650,.25,'triangle',0,.09,950);t(950,.2,'triangle',.2,.08,480);break;case'impact':case'enemy':t(110,.22,'triangle',0,.25,40);break;case'rope':t(1400,.07,'sawtooth',0,.06,240);break;case'fire':t(80,.13,'sawtooth',0,.025,45);break;case'pin':t(1100,.12,'triangle',0,.1,450);break;default:t(780,.08,'sine');}}
};
